### ISSUE TITLE
Collaborator

### ISSUE THREAD

**Issue by PiSaucer** [Decotron99/Schoolgrounds#2]
![image](https://user-images.githubusercontent.com/33438654/113233483-eb7aa380-9264-11eb-880e-2d1d7eeaa90e.png)

In the pull request, you say that I was a collaborator but I don't have the write access to help you guys.

**Comment by Decotron99** [comment]
you need to accept the collaborator invite :)

**Comment by PiSaucer** [comment]
Ah, I didn't see the email.
